create table sysuser (
 user_id bigint generated by default as identity primary key,
 first_name varchar(100) not null, last_name varchar(100) not null,
 user_name varchar(220) not null unique, email varchar(254) not null unique,
 role varchar(255) not null, registration_date date not null
);
create table supplier (
 supplier_id bigint generated by default as identity primary key,
 name varchar(100) not null unique, normalized_name varchar(100) not null unique, company_number varchar(12) not null unique,
 established_date date
);
create table ingredient (
 ingredient_id bigint generated by default as identity primary key,
 name varchar(100) not null, unit varchar(255) not null
);
create table product (
 product_id bigint generated by default as identity primary key,
 name varchar(100) not null, description varchar(2000),
 retail_price numeric(14,2) not null check (retail_price > 0), status varchar(255) not null
);
create table recipe_mapping (
 product_id bigint not null references product(product_id),
 ingredient_id bigint not null references ingredient(ingredient_id),
 quantity numeric(14,3) not null check (quantity > 0),
 primary key (product_id, ingredient_id)
);
create table stock_item (
 stock_item_id bigint generated by default as identity primary key,
 supplier_id bigint not null references supplier(supplier_id),
 name varchar(100) not null, description varchar(2000),
 retail_price numeric(14,2) not null check (retail_price > 0)
);
create table stock_record (
 stock_record_id bigint generated by default as identity primary key,
 stock_item_id bigint not null references stock_item(stock_item_id),
 incoming_date date not null, expiry_date date not null,
 quantity numeric(14,3) not null check (quantity > 0),
 condition_status varchar(255) not null, storage varchar(255) not null,
 check (expiry_date >= incoming_date)
);
create table customer_order (
 customer_order_id bigint generated by default as identity primary key,
 user_id bigint not null references sysuser(user_id),
 order_time_stamp timestamp not null, status varchar(255) not null,
 version bigint not null default 0
);
create table customer_order_item (
 customer_order_id bigint not null references customer_order(customer_order_id),
 product_id bigint not null references product(product_id),
 quantity integer not null check (quantity > 0),
 unit_price numeric(14,2) not null check (unit_price > 0),
 primary key (customer_order_id, product_id)
);
create index recipe_ingredient_idx on recipe_mapping(ingredient_id);
create index stock_supplier_idx on stock_item(supplier_id);
create index receipt_item_date_idx on stock_record(stock_item_id, incoming_date);
create index order_creator_idx on customer_order(user_id);
create index order_product_idx on customer_order_item(product_id);
